spring.profiles.active: local

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/thor?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: ghdrn123

server:
  port: 8443
  ssl:
    enabled: true # Uses self-signed certificate because no key-store configuration is specified.

# Additional server ports specified with Armeria configuration.
armeria:
  ports:
    - port: 8443    # Port 8443 will serve HTTPS, HTTP and PROXY protocol.
      protocols:
        - http
        - proxy
    - port: 8080    # Port 8080 will serve only HTTP.
      protocol: http